language: ruby
rvm:
  - 2.4.0

addons:
  code_climate:
    repo_token: 89943dcf9eece00c7e360730a4a6102b1ce29c1b9956186bf4801ad059169274

env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000
    - SECURITY_SECRET_TOKEN=traviscitraviscitraviscitraviscitravisci

services:
  - postgresql
  - redis-server

before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  # Solves rainbow issue: https://github.com/sickill/rainbow/issues/48
  - gem update --system

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c "CREATE USER \"rails-bootstrap\" WITH PASSWORD 'rails-bootstrap';" -U postgres
  - psql -c "DROP DATABASE IF EXISTS \"rails-bootstrap_test\";" -U postgres
  - psql -c "CREATE DATABASE \"rails-bootstrap_test\" ENCODING 'utf8';" -U postgres
  - bundle exec rake db:migrate

script:
  - bundle exec rspec spec -fd
  - bundle exec rubocop app spec -R --format simple
  - bundle exec scss-lint app/assets/stylesheets/

#notifications:
#  email:
#    recipients:
#      - rails-bootstrap-dev@wolox.com.ar

cache:
  bundler: true
